import Head from 'next/head'
import { Hero, FilterSection } from '#components'
import { Typography } from '#atoms'

export default function Home() {
  return (
    <>
      <Head>
        <title>Premier League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <FilterSection />
      </main>
    </>
  )
}
